[server]
headless = true
port = 8501
enableCORS = false

[theme]
base="light"
primaryColor="#d63384"
backgroundColor="#ffffff"
secondaryBackgroundColor="#f0f2f6"
textColor="#000000"
font="sans serif"
